using HarmonyLib;
using Kingmaker.Blueprints.JsonSystem;
using Kingmaker.Utility;


namespace SpellbookMerge.Patches
{
    // ReSharper disable once UnusedType.Global
    internal static class LogBlueprints
    {
        [HarmonyPatch(typeof(BlueprintsCache), "Init")]
        // ReSharper disable once UnusedType.Local
        private static class BlueprintsLogGuids
        {
            [HarmonyPriority(Priority.Last)]
            // ReSharper disable once UnusedMember.Local
            private static void Postfix() {
                GenerateUnused();
                Main.ModSettings.Blueprints.SaveTo(Main.UserConfigDir!);
            }

            private static void GenerateUnused() {
                Main.ModSettings.Blueprints.AutoGenerated.ForEach(entry =>
                {
                    var (key, value) = entry;
                    if (!Main.ModSettings.Blueprints.UsedGuids.ContainsKey(key)) {
                        Main.ModSettings.Blueprints.UnusedGuids[key] = value;
                    }
                });
                Main.ModSettings.Blueprints.NewBlueprints.ForEach(entry =>
                {
                    var (key, value) = entry;
                    if (!Main.ModSettings.Blueprints.UsedGuids.ContainsKey(key)) {
                        Main.ModSettings.Blueprints.UnusedGuids[key] = value;
                    }
                });
            }
        }
        
    }
}